export const datos = {
    ofertasTrabajo: [ 
        { titulo: "Farmacéutico/a en consultorio médico",
        fecha: "2026-02-17",
        descripcion: "Se precisa de un técnico farmacéutico colegiado para distribuir medicación.",
        categoria: "Servicio Sanitario (área rural)",
        ubicacion: "Aínsa",
        publicacion_usuario: "R. García",
        etiqueta_color:"",
    },
    {  titulo: "Carpintero/a media jornada",
        fecha: "2026-02-26",
        descripcion: "Se ofrece media jornada a persona con experiencia en el tratamiento y manipulación de la madera. Turno de mañana (9:30-13:30h) o tarde (15:30 - 19:30h) a elección de la persona.",
        categoria: "Oficio",
        ubicacion: "Carrizo - León",
        publicacion_usuario: "S. Mendoza",
        etiqueta_color: "",
     },
     {  titulo: "Técnico de sistemas de la información (Ayuntamiento)",
        fecha: "2026-02-26",
        descripcion: "Gestor y administrador de el sistema informático.",
        categoria: "Profesional servicios TIC",
        ubicacion: "Mediola - Bizkaia",
        publicacion_usuario: "Ayuntamineto Mediola",
        etiqueta_color: "",
     },
      {  titulo: "Técnico auxiliar veterinario rural",
        fecha: "2026-02-28",
        descripcion: "Plaza de técnico veterinario en asistencia rural a granjas. Sobretodo se asiste a bovino, ovino y caprino. Puntualmente cinegéticos.",
        categoria: "Colegiado Veterinaria",
        ubicacion: "Burguillos de Toledo",
        publicacion_usuario: "Clínica Veterinaria Burguillos",
        etiqueta_color: "",
     },
      {  titulo: "Asistente social zona rural (Ayuntamiento Vilamacolum)",
        fecha: "2026-03-05",
        descripcion: "Profesional en asistencia social combinando visitas domicialiarias y teletrabajo",
        categoria: "Profesional asistencia social",
        ubicacion: "Vilamacolum - Girona",
        publicacion_usuario: "G.Martín",
        etiqueta_color: "",
     },  
      {  titulo: "Repostero/panadero",
        fecha: "2026-03-05",
        descripcion: "Se ofrece puesto de trabajo a personal que haya tenido contacto con la panadería y respostería. Se formará a la persona.",
        categoria: "Oficial 1ª categoria",
        ubicacion: "Turre - Almería",
        publicacion_usuario: "P. Pérez",
        etiqueta_color: "",
     }, 
    {  titulo: "Auditor/a certificación ecológico (CCPAE)",
        fecha: "2026-03-14",
        descripcion: "Trabajo híbrido de campo (inspecciones y adutorías in situ) y teletrabajo con la emisión de informes de auditoria.",
        categoria: "Técnico auditor",
        ubicacion: "Les Preses - Olot, Girona",
        publicacion_usuario: "Entidad CCPAE",
        etiqueta_color: "",
     },  
    ],

    demandasTrabajo: [
        {
            titulo: "Se ofrece persona qualificada para trabajos de oficio varios",
            fecha: "2026-02-21",
            descripcion: "En búsqueda de trabajo como técnico electricista, fontanero o carpintero.",
            ubicacion: "Zona Huesca (Aragón)",
            publicacion_usuario: "F. Muñoz",
            etiqueta_color: "",
        },
           {
            titulo: "Técnico informático en búsqueda de trabajo (presencial/remoto)",
            fecha: "2026-02-25",
            descripcion: "Se ofrece persona qualificada para tareas de IT y gestión de sistemas.",
            ubicación: "Sin requerimientos",
            publicacion_usuario: " N. Valls",
            etiqueta_color: "",
        },
           {
            titulo: "Persona se ofrece para trabajo en tareas de agricultura y ramaderia",
            fecha: "2026-03-09",
            descripcion: "He desarrollado trabajos de todo tipo, en muchos países, ahora busco un trabajo en zona rural para poder desarrollar mi propio proyecto.",
            ubicacion: "Porvincia de Girona",
            publicacion_usuario: "M. Martinez",
            etiqueta_color: "",
        },
           {
            titulo: "Infermero busco trabajo en consultorios rurales.",
            fecha: "2026-03-12",
            descripcion: "Busco un trabajo en centros médicos o consultorios.",
            ubicacion: "Zona Navarra",
            publicacion_usuario: "L. Cavalcantio",
            etiqueta_color: "",
        },
    ],

    UsusariosRegistrados: [
        {
            id: "001",
            nombre: "Fernando Muñoz",
            email: "fernando_munoz@gmail.com",
        },
        
        {
            id: "002",
            nombre: "Gonzalo Martín",
            email: "gon.m88@hotmail.com",
        }
    ]
}